# Generated by Django 4.2 on 2024-10-17 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_category_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="catergory",
            new_name="category",
        ),
    ]
